SELECT
  DEPARTAMENTOS.NOMBRE AS DEPARTAMENTO,
  CIUDADES.NOMBRE      AS CIUDAD,
  PUNTOS_VOTACIONS.DIRECCION,
  MESAS_VOTACIONS.NUMERO,
  MESAS_VOTACIONS.ID,
  USERS.NAME||' '||
  USERS.NAME2||' '||
  USERS.LASTNAME||' '|| 
  USERS.LASTNAME2 NOMBRECOMPLETO
FROM
  DEPARTAMENTOS
INNER JOIN CIUDADES
ON
  DEPARTAMENTOS.ID=CIUDADES.ID_DEPARTAMENTO
INNER JOIN PUNTOS_VOTACIONS
ON
  CIUDADES.ID=PUNTOS_VOTACIONS.ID_CIUDAD
INNER JOIN MESAS_VOTACIONS
ON
  PUNTOS_VOTACIONS.ID=MESAS_VOTACIONS.ID_PUNTO
INNER JOIN USERS
ON
  MESAS_VOTACIONS.ID=USERS.ID_MESA
WHERE
  MESAS_VOTACIONS.NUMERO LIKE '%s$buscar$s%'
OR PUNTOS_VOTACIONS.DIRECCION LIKE '%s$buscar$s%'
OR CIUDADES.NOMBRE LIKE '%s$buscar$s%'
OR DEPARTAMENTOS.NOMBRE LIKE '%s$buscar$s%'
ORDER BY
  MESAS_VOTACIONS.ID